name: First Workflow  # name of workflow
on:
  push:
    branches:
      - main
jobs:
  first-job: # name of job (can be customized)
    runs-on: ubuntu-latest # runner e.g. execution environment (for example a GitHub-Hosted Runner)
    steps:
      - name: Step with shell command
        run: echo "Hi first workflow"
      - name: Step with action
        uses: actions/setup-python@v5
      - name: Install pylint
          run: pip install pylint
      - name: Do Tests
          run: pylint