name: First Workflow  # name of workflow
on: push # event that triggers the execution, 'workflow_dispatch' is a manual trigger
jobs:
  first-job: # name of job (can be customized)
    runs-on: ubuntu-latest # runner e.g. execution environment (for example a GitHub-Hosted Runner)
    steps:
      - name: Step with shell command
        run: echo "Hello World"
      - name: Step with action
        uses: actions/setup-python@v5